"""Default configuration for LVCR ISMIR 2019 package."""
import os

JAM_DATASET_PATH = os.getenv('LVCR_JAM_DATASET_PATH', '')
MY_DATASET_PATH = os.getenv('LVCR_MY_DATASET_PATH', '')
OSU_KEY_DATASET_PATH = os.getenv('LVCR_OSU_KEY_DATASET_PATH', '')
MISC_DATASET_PATH = os.getenv('LVCR_MISC_DATASET_PATH', '')
BEATLES_DATASET_PATH = os.getenv('LVCR_BEATLES_DATASET_PATH', '')
RWC_DATASET_PATH = os.getenv('LVCR_RWC_DATASET_PATH', '')
USPOP_DATASET_PATH = os.getenv('LVCR_USPOP_DATASET_PATH', '')
BILLBOARD_DATASET_PATH = os.getenv('LVCR_BILLBOARD_DATASET_PATH', '')
KARAOKE_DATASET_PATH = os.getenv('LVCR_KARAOKE_DATASET_PATH', '')
CB_DATASET_PATH = os.getenv('LVCR_CB_DATASET_PATH', '')
CB_BOOTSTRAP_DATASET_PATH = os.getenv('LVCR_CB_BOOTSTRAP_DATASET_PATH', '')

DEFAULT_SR = 22050
DEFAULT_HOP_LENGTH = 512
DEFAULT_BEAT_HOP_LENGTH = 512
DEFAULT_WIN_SIZE = 8192
DEFAULT_CHROMA_TUPLE_SIZE = 2
DEFAULT_CHORD_DICT = 'mirex'
